### ISSUE TITLE
Acessar estatísticas do cronômetro

### ISSUE THREAD

**Issue by diogopaz** [enzo-s-azevedo/estudAI#2]
Como estudante eu quero acessar um cronômetro para acessar as estatísticas
Critérios de aceitação
- [x] #55
- [ ] O sistema deve mostrar a média diária de tempo estudado
- [ ] O sistema deve mostrar o tempo diário de estudo
- [ ] O sistema deve mostrar o dia recorde de tempo estudado.

**Comment by enzo-s-azevedo** [comment]
Como estudante eu quero acessar um cronometro para acessar as estatísticas
       Criterios de aceitação:
                 O sistema deve mostrar as estatísticas sobre o meu uso do cronômetro: média diária de tempo estudado, tempo diário de estudo, dia recorde de tempo estudado.
